### 5.2.1  卷积函数

此示例说明使用w = conv(u, v) 返回向量u和v的卷积。如果u和v是多项式系数的向量，对其卷积与将这两个多项式相乘等效。
使用w = conv(u,v,shape) 返回shape指定的卷积的分段。例如，conv(u, v,"same")仅返回与u等大小的卷积的中心部分，而conv(u,v,"valid")仅返回计算的没有补零边缘的卷积部分。

通过卷积计算多项式乘法:
创建包含多项式 x^2+1 和 2x+7 的系数的向量 u 和 v。

In [1]:
using TyMath
u = [1,0,1]
v = [2,7]

2-element Vector{Int64}:
 2
 7

使用卷积将多个多项式相乘。

In [2]:
w = conv(u,v)

4-element Vector{Int64}:
 2
 7
 2
 7

向量卷积：
创建两个向量并求其卷积。

In [3]:
using TyMath
u = [1,1,1]
v = [1,1,0,0,0,1,1]
w = conv(u,v)

9-element Vector{Int64}:
 1
 2
 2
 1
 0
 1
 2
 2
 1

卷积的中心部分：
创建两个向量。计算与 u 大小相同的 u 和 v 的卷积的中心部分。

In [4]:
using TyMath
u = [-1,2,3,-2,0,1,2]
v = [2,4,-1,1]
w = conv(u,v,"same")

7-element Vector{Int64}:
 15
  5
 -9
  7
  6
  7
 -1

二维卷积：
C = conv2(A,B) 返回矩阵 A 和 B 的二维卷积。
C = conv2(u,v,A) 首先求 A 的各列与向量 u 的卷积，然后求每行结果与向量 v 的卷积。
C = conv2(___,shape) 根据 shape 返回卷积的子区。例如，C = conv2(A,B,"same") 返回卷积中大小与 A 相同的中心部分。

示例：
在图像处理等应用程序中，它可用于将卷积的输入直接与输出进行比较。conv2 函数允许您控制输出的大小。
创建一个 3×3 随机矩阵 A 和一个 4×4 随机矩阵 B。计算 A 和 B 的完整卷积，结果是一个 6×6 矩阵。

In [5]:
using TyMath
A = rand(3,3)
B = rand(4,4)
Cfull = conv2(A,B)

6×6 Matrix{Float64}:
 0.0462204  0.666478  0.815172  0.68267   0.225046  0.00320177
 0.331561   0.358427  0.885391  0.594694  0.581877  0.0630982
 0.422862   1.00703   1.51233   1.79657   1.52382   0.450856
 0.107388   0.532647  1.17044   1.46782   1.34967   0.74498
 0.237531   0.357642  1.35161   1.7094    1.7485    0.518864
 0.220673   0.54517   0.88444   0.796857  0.4341    0.0456478

计算卷积 Csame 的中心部分，它是 Cfull 的子矩阵，大小与 A 相同。Csame 等于 Cfull[3:5,3:5]。

In [6]:
Csame = conv2(A,B,"same")

3×3 Matrix{Float64}:
 1.51233  1.79657  1.52382
 1.17044  1.46782  1.34967
 1.35161  1.7094   1.7485

提取二维台座边：
Sobel 求边运算利用二维卷积来检测图像的边和其他二维数据。
创建并绘制一个内部高度等于 1 的二维台座。

In [7]:
using TyMath
using TyPlot
A = zeros(10,10)
A[3:7,3:7] .= ones(5,5)
mesh(A)

PyObject <mpl_toolkits.mplot3d.art3d.Poly3DCollection object at 0x000001FCA13CC4C8>

首先求 A 的各行与向量 u 的卷积，然后求卷积结果的各行与向量 v 的卷积。卷积提取台座的水平边。

In [8]:
u = [1,0,-1]
v = [1,2,1]
Ch = conv2(u,v,A)
mesh(Ch)

PyObject <mpl_toolkits.mplot3d.art3d.Poly3DCollection object at 0x000001FC9C6507C8>

要提取台座的垂直边，请反转与 u 和 v 的卷积顺序。

In [9]:
Cv  = conv2(v,u,A)
mesh(Cv)

PyObject <mpl_toolkits.mplot3d.art3d.Poly3DCollection object at 0x000001FC9C8B3348>

计算并绘制台座的组合边。

In [10]:
figure()
mesh(sqrt.(Ch.^2 + Cv.^2))

PyObject <mpl_toolkits.mplot3d.art3d.Poly3DCollection object at 0x000001FCA4A92408>